INSERT INTO roles(name) VALUES ('ROLE_CREDIT_OFFICER');
INSERT INTO roles(name) VALUES ('ROLE_SUPERVISOR');
INSERT INTO roles(name) VALUES ('ROLE_OFFICE_ADMIN');
INSERT INTO roles(name) VALUES ('ROLE_LOAN_APPLICANT');
